version: "3.9"

services:
  grafana:
    image: grafana/grafana-oss
    container_name: daf-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - daf

  mysql:
    image: mysql
    container_name: daf-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - daf:/var/lib/mysql
    networks:
      - daf

volumes:
  daf:
  grafana:

networks:
  daf:
